### PR TITLE
Documentation with sphinx, pylint code cleaning

### PR DESCRIPTION
**Pull request by eacharles**
These shouldn't have any actually functional changes.  I was just being fussy and wanted to see nice html documentation.

### CODE REVIEW

**Review by kadrlica — APPROVED** [review]
Looks awesome to me!

**Comment by kadrlica** [comment]
@eacharles do you want to merge, or do you want me to?

**Comment by eacharles** [comment]
Go for it, and is it ok to tag and publish the new tag?

And can you give me the keys to do that?

-e

**Comment by kadrlica** [comment]
Ok, it's merged and I've given you the keys to pypi.

**Pull request merged**
